language: python
python:
  - '3.5'
before_install:
  - rvm install 2.0.0-p648
  - bundle install
  - pip3 install pytest
script: source test_runner.sh

# language: python
# python:
#   - '3.5'
# before_install:
#   - pip install pytest
# script:
#   - py.test python/
